[package]
name = "speexdp-common"
version = "0.1.0"
edition = "2021"

[features]
default = []
userspace = [ "aya" ]

[dependencies]
aya = { path = "/tmp/aya/aya", version = ">=0.11", optional=true }

[lib]
path = "src/lib.rs"
